<h2>Manage Certificate of Employment Requests</h2>
<hr/>
<ul class="tabs">
	<li class="tab-link current" data-tab="tab-1">Pending COE Requests (<?= count($pending) ?>)</li>
	<li class="tab-link" data-tab="tab-2">Generated Requests</li>
</ul>
<div id="tab-1" class="tab-content current">	
<table class="tableInfo">
	<tr class="trhead">
		<td>Employee's Name</td>
		<td>Date Requested</td>
		<td>Purpose of Request</td>
		<td>Note for HR</td>
		<td><br/></td>
	</tr>
<?php
	if(count($pending)==0){
		echo '<tr><td colspan=3>No pending requests.</td></tr>';
	}else{
		foreach($pending AS $p):
			echo '<tr>';
				echo '<td><a href="'.$this->config->base_url().'staffinfo/'.$p->username.'/">'.$p->name.'</a></td>';
				echo '<td>'.date('F d, Y', strtotime($p->daterequested)).'</td>';
				echo '<td>'.$p->purpose.'</td>';
				echo '<td>'.$p->notesforHR.'</td>';
			if($p->dateissued!='0000-00-00')
				echo '<td align="center"><a class="iframe" href="'.$this->config->base_url().'requestcoe/'.$p->coeID.'/"><img src="'.$this->config->base_url().'css/images/pdf-icon.png"/></a></td>';
			else
				echo '<td align="center"><button class="iframe padding5px" href="'.$this->config->base_url().'requestcoe/'.$p->coeID.'/">Generate Options</button></td>';
			echo '</tr>';
		endforeach;
	}
?>
	
</table>
</div>
<br/>
<div id="tab-2" class="tab-content">	
<table class="tableInfo datatable">
<thead>
	<tr class="trhead">
		<td>Employee's Name</td>
		<td>Date Requested</td>
		<td>Purpose of Request</td>
		<td>Note to HR</td>
		<td>Generated By</td>
		<td>Date Generated</td>
		<td><br/></td>
	</tr>
</thead>
<?php
	if(count($printed)==0){
		echo '<tr><td colspan=3>No printed requests.</td></tr>';
	}else{
		foreach($printed AS $p):
			echo '<tr>';
				echo '<td><a href="'.$this->config->base_url().'staffinfo/'.$p->username.'/">'.$p->name.'</a></td>';
				echo '<td>'.date('F d, Y', strtotime($p->daterequested)).'</td>';
				echo '<td>'.$p->purpose.'</td>';
				echo '<td>'.$p->notesforHR.'</td>';
				echo '<td>'.$p->genName.'</td>';
				echo '<td>'.date('F d, Y', strtotime($p->dateissued)).'</td>';
				echo '<td align="center"><a class="iframe" href="'.$this->config->base_url().'requestcoe/'.$p->coeID.'/"><img src="'.$this->config->base_url().'css/images/pdf-icon.png"/></a></td>';
			echo '</tr>';
		endforeach;
	}
?>
	
</table>
</div>
